import { Colors } from '@/constants/theme';
import { useSession } from '@/context/session';
import { apiRequest } from '@/lib/api';
import { Branch } from '@/lib/types';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, useColorScheme, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function ExploreScreen() {
  const color = Colors[useColorScheme() === 'dark' ? 'dark' : 'light']; const { token } = useSession();
  const [branches, setBranches] = useState<Branch[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useFocusEffect(useCallback(() => { if (!token) return; let active = true; setLoading(true); apiRequest<{ data: Branch[] }>('/customer/branches', token).then((response) => active && setBranches(response.data)).catch((reason) => active && setError(reason.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, [token]));
  const filtered = useMemo(() => branches.filter((branch) => `${branch.name} ${branch.address} ${branch.services.map((service) => service.name).join(' ')}`.toLowerCase().includes(search.toLowerCase())), [branches, search]);

  if (!token) return <SafeAreaView style={[styles.screen, { backgroundColor: color.background }]}><View style={styles.center}><Text style={[styles.title, { color: color.text }]}>Explore branches</Text><Text style={[styles.copy, { color: color.textSecondary }]}>Sign in to see live queues and service availability.</Text><Pressable onPress={() => router.push('/login')} style={[styles.button, { backgroundColor: color.primary }]}><Text style={styles.buttonText}>Sign in</Text></Pressable></View></SafeAreaView>;

  return <SafeAreaView style={[styles.screen, { backgroundColor: color.background }]} edges={['top']}><ScrollView contentContainerStyle={styles.content}><Text style={[styles.eyebrow, { color: color.primary }]}>BRANCH DISCOVERY</Text><Text style={[styles.title, { color: color.text }]}>Find your nearest queue</Text><TextInput value={search} onChangeText={setSearch} placeholder="Search branches or services" placeholderTextColor={color.textSecondary} style={[styles.search, { backgroundColor: color.backgroundElement, borderColor: color.border, color: color.text }]} />
    <View style={styles.filterRow}><View style={[styles.filter, { backgroundColor: color.primary }]}><Text style={styles.filterActive}>All branches</Text></View><View style={[styles.filter, { backgroundColor: color.backgroundElement }]}><Text style={{ color: color.textSecondary, fontWeight: '800' }}>Open now</Text></View></View>
    {loading && <ActivityIndicator color={color.primary} />}{error ? <Text style={styles.error}>{error}</Text> : null}{filtered.map((branch) => { const waits = branch.services.map((service) => service.queue.estimated_wait_minutes).filter((wait): wait is number => wait !== null); const wait = waits.length ? Math.min(...waits) : null; return <Pressable key={branch.id} onPress={() => router.push({ pathname: '/branch/[id]', params: { id: branch.id } })} style={[styles.card, { backgroundColor: color.backgroundElement, borderColor: color.border }]}><View style={styles.cardTop}><View style={[styles.marker, { backgroundColor: color.backgroundSelected }]}><Text style={{ color: color.primary, fontSize: 23 }}>▥</Text></View><View style={styles.info}><Text style={[styles.name, { color: color.text }]}>{branch.name}</Text><Text numberOfLines={1} style={[styles.address, { color: color.textSecondary }]}>{branch.address}</Text></View><Text style={[styles.arrow, { color: color.text }]}>›</Text></View><View style={styles.stats}><View><Text style={[styles.statValue, { color: branch.is_open ? color.success : color.textSecondary }]}>{branch.is_open ? 'Open' : 'Closed'}</Text><Text style={[styles.statLabel, { color: color.textSecondary }]}>Status</Text></View><View><Text style={[styles.statValue, { color: color.text }]}>{branch.services.length}</Text><Text style={[styles.statLabel, { color: color.textSecondary }]}>Services</Text></View><View><Text style={[styles.statValue, { color: color.text }]}>{wait === null ? '—' : `${wait} min`}</Text><Text style={[styles.statLabel, { color: color.textSecondary }]}>Shortest wait</Text></View></View><View style={styles.chips}>{branch.services.slice(0,3).map((service) => <Text key={service.id} style={[styles.chip, { color: color.primaryDark, backgroundColor: color.backgroundSelected }]}>{service.name}</Text>)}</View></Pressable>; })}
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 18, paddingBottom: 40 }, center: { flex: 1, justifyContent: 'center', padding: 28 }, eyebrow: { fontSize: 10, fontWeight: '900', letterSpacing: 1.4 }, title: { fontSize: 30, lineHeight: 36, fontWeight: '900', letterSpacing: -1, marginTop: 7 }, copy: { fontSize: 16, lineHeight: 24, marginTop: 10 }, button: { marginTop: 24, height: 50, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, buttonText: { color: 'white', fontWeight: '900' }, search: { height: 50, borderWidth: 1, borderRadius: 16, paddingHorizontal: 16, marginTop: 20, fontSize: 14 }, filterRow: { flexDirection: 'row', gap: 8, marginVertical: 16 }, filter: { paddingHorizontal: 14, paddingVertical: 9, borderRadius: 12 }, filterActive: { color: 'white', fontWeight: '900' }, error: { color: '#B42345', marginBottom: 10 }, card: { borderWidth: 1, borderRadius: 22, padding: 15, marginBottom: 12 }, cardTop: { flexDirection: 'row', alignItems: 'center' }, marker: { width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, info: { flex: 1, marginLeft: 12 }, name: { fontSize: 17, fontWeight: '900' }, address: { marginTop: 4, fontSize: 12 }, arrow: { fontSize: 29 }, stats: { marginTop: 16, flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#DDE7F5', paddingTop: 14 }, statValue: { fontSize: 14, fontWeight: '900' }, statLabel: { marginTop: 2, fontSize: 10 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 14 }, chip: { fontSize: 10, fontWeight: '800', paddingHorizontal: 9, paddingVertical: 6, borderRadius: 9 } });
