import { Colors } from '@/constants/theme';
import { useSession } from '@/context/session';
import { ApiError, apiRequest } from '@/lib/api';
import { Branch, Ticket } from '@/lib/types';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, useColorScheme, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { usePreferences } from '@/context/preferences';

export default function HomeScreen() {
  const color = Colors[useColorScheme() === 'dark' ? 'dark' : 'light'];
  const { token, user } = useSession();
  const { language, toggleLanguage, t } = usePreferences();
  const [branches, setBranches] = useState<Branch[]>([]);
  const [ticket, setTicket] = useState<Ticket | null>(null);
  const [loading, setLoading] = useState(false);

  useFocusEffect(useCallback(() => {
    if (!token) { setBranches([]); setTicket(null); return; }
    let active = true; setLoading(true);
    Promise.all([
      apiRequest<{ data: Branch[] }>('/customer/branches', token),
      apiRequest<{ data: Ticket }>('/tickets/active', token).catch((error) => error instanceof ApiError && error.status === 404 ? null : Promise.reject(error)),
    ]).then(([branchResponse, ticketResponse]) => {
      if (active) { setBranches(branchResponse.data); setTicket(ticketResponse?.data ?? null); }
    }).finally(() => active && setLoading(false));
    return () => { active = false; };
  }, [token]));

  if (!token) {
    return <SafeAreaView style={[styles.screen, { backgroundColor: color.background }]}><View style={styles.signedOut}><View style={[styles.logo, { backgroundColor: color.primary }]}><Text style={styles.logoText}>Q</Text></View><Text style={[styles.hero, { color: color.text }]}>Less waiting.{`\n`}More living.</Text><Text style={[styles.lead, { color: color.textSecondary }]}>Sign in to discover open branches, reserve your number, and follow your turn.</Text><Pressable onPress={() => router.push('/login')} style={[styles.primaryButton, { backgroundColor: color.primary }]}><Text style={styles.primaryText}>Sign in to QueueCare</Text></Pressable><Text style={[styles.demo, { color: color.textSecondary }]}>Demo: customer@queuecare.test · password</Text></View></SafeAreaView>;
  }

  const firstBranch = branches[0];
  const popular = branches.flatMap((branch) => branch.services.map((service) => ({ ...service, branchId: branch.id }))).slice(0, 4);
  return <SafeAreaView style={[styles.screen, { backgroundColor: color.background }]} edges={['top']}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.topbar}><View><Text style={[styles.brand, { color: color.primaryDark }]}>QueueCare</Text><Text style={[styles.greeting, { color: color.text }]}>{t('greeting')}, {user?.name.split(' ')[0]}</Text><Text style={[styles.subtitle, { color: color.textSecondary }]}>{t('smoother')}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Switch language" onPress={toggleLanguage} style={[styles.languageButton, { backgroundColor: color.backgroundElement, borderColor: color.border }]}><Text style={{ color: color.primaryDark, fontWeight: '900' }}>{language === 'en' ? 'ខ្មែរ' : 'EN'}</Text></Pressable></View>
    {loading && <ActivityIndicator color={color.primary} />}
    {ticket ? <Pressable accessibilityRole="button" accessibilityLabel={`${t('yourQueue')} ${ticket.number}`} onPress={() => router.push('/ticket')} style={[styles.ticket, { backgroundColor: color.backgroundElement, borderColor: color.border }]}><View style={styles.row}><View style={[styles.icon, { backgroundColor: color.backgroundSelected }]}><Text style={{ color: color.primary }}>●●</Text></View><Text style={[styles.cardTitle, { color: color.text }]}>{t('yourQueue')}</Text><Text style={[styles.arrow, { color: color.text }]}>›</Text></View><View style={styles.ticketMain}><View><Text style={[styles.number, { color: color.primaryDark }]}>{ticket.number}</Text><Text style={[styles.ahead, { color: color.text }]}>{ticket.people_ahead} {ticket.people_ahead === 1 ? 'person' : 'people'} ahead</Text></View><View style={[styles.wait, { backgroundColor: color.backgroundSelected }]}><Text style={[styles.waitLabel, { color: color.textSecondary }]}>{t('estimatedWait')}</Text><Text style={[styles.waitValue, { color: color.primaryDark }]}>{ticket.estimated_wait_minutes === null ? '—' : `${ticket.estimated_wait_minutes} min`}</Text></View></View><View style={styles.progress}>{[0,1,2,3,4,5].map((step) => <View key={step} style={[styles.progressDot, { backgroundColor: step < Math.min(5, Math.max(1, 5 - ticket.people_ahead)) ? color.primary : color.border }]} />)}</View><Text style={[styles.helper, { color: color.textSecondary }]}>{t('liveStatus')}</Text></Pressable> : <View style={[styles.emptyTicket, { backgroundColor: color.primaryDark }]}><Text style={styles.emptyTag}>QUEUECARE</Text><Text style={styles.emptyTitle}>{t('noTicket')}</Text><Text style={styles.emptyCopy}>{t('noTicketCopy')}</Text><Pressable accessibilityRole="button" onPress={() => router.push('/explore')} style={[styles.lightButton, { backgroundColor: color.backgroundElement }]}><Text style={{ color: color.primary, fontWeight: '800' }}>{t('findBranch')}</Text></Pressable></View>}
    {firstBranch && <Pressable onPress={() => router.push({ pathname: '/branch/[id]', params: { id: firstBranch.id } })} style={[styles.branchCard, { backgroundColor: color.backgroundElement, borderColor: color.border }]}><View style={[styles.pin, { backgroundColor: color.primary }]}><Text style={styles.pinText}>●</Text></View><View style={styles.branchInfo}><Text style={[styles.branchName, { color: color.text }]}>{firstBranch.name}</Text><Text style={[styles.branchMeta, { color: firstBranch.is_open ? color.success : color.textSecondary }]}>{firstBranch.is_open ? '● Open now' : '● Closed'} · {firstBranch.services.length} services</Text><Text numberOfLines={1} style={[styles.address, { color: color.textSecondary }]}>{firstBranch.address}</Text></View><Text style={[styles.arrow, { color: color.text }]}>›</Text></Pressable>}
    <View style={styles.sectionRow}><Text style={[styles.sectionTitle, { color: color.text }]}>{t('popular')}</Text><Text onPress={() => router.push('/explore')} style={[styles.seeAll, { color: color.primary }]}>{t('seeAll')}</Text></View><View style={styles.serviceGrid}>{popular.map((service, index) => <Pressable key={`${service.branchId}-${service.id}`} onPress={() => router.push({ pathname: '/branch/[id]', params: { id: service.branchId } })} style={[styles.serviceCard, { backgroundColor: color.backgroundElement, borderColor: color.border }]}><View style={[styles.serviceIcon, { backgroundColor: [color.backgroundSelected, '#DDF8EF', '#FFF0CE', '#EFE8FF'][index % 4] }]}><Text style={{ color: color.primary, fontWeight: '900' }}>{service.code.slice(0,2)}</Text></View><Text numberOfLines={1} style={[styles.serviceName, { color: color.text }]}>{service.name}</Text><Text style={[styles.serviceWait, { color: color.textSecondary }]}>{service.queue.estimated_wait_minutes === null ? '—' : `~${service.queue.estimated_wait_minutes} min`}</Text></Pressable>)}</View>
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({
  screen: { flex: 1 }, content: { padding: 18, paddingBottom: 42, gap: 14 }, signedOut: { flex: 1, justifyContent: 'center', padding: 28 }, logo: { width: 56, height: 56, borderRadius: 20, alignItems: 'center', justifyContent: 'center' }, logoText: { color: 'white', fontSize: 28, fontWeight: '900' }, hero: { marginTop: 32, fontSize: 45, lineHeight: 50, fontWeight: '900', letterSpacing: -1.5 }, lead: { marginTop: 18, fontSize: 17, lineHeight: 26 }, primaryButton: { marginTop: 32, height: 54, borderRadius: 17, alignItems: 'center', justifyContent: 'center' }, primaryText: { color: 'white', fontSize: 16, fontWeight: '900' }, demo: { marginTop: 16, textAlign: 'center', fontSize: 12 },
  topbar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 5 }, brand: { fontSize: 19, fontWeight: '900' }, greeting: { marginTop: 16, fontSize: 26, fontWeight: '900', letterSpacing: -0.7 }, subtitle: { marginTop: 2, fontSize: 14 }, languageButton: { minWidth: 58, height: 42, borderWidth: 1, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginLeft: 8 },
  ticket: { borderWidth: 1, borderRadius: 24, padding: 16 }, row: { flexDirection: 'row', alignItems: 'center', gap: 9 }, icon: { width: 34, height: 34, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, cardTitle: { fontSize: 16, fontWeight: '900' }, arrow: { marginLeft: 'auto', fontSize: 30 }, ticketMain: { marginTop: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, number: { fontSize: 36, fontWeight: '900' }, ahead: { fontSize: 14, fontWeight: '700' }, wait: { borderRadius: 15, padding: 12, alignItems: 'center' }, waitLabel: { fontSize: 10 }, waitValue: { fontSize: 19, fontWeight: '900', marginTop: 2 }, progress: { marginTop: 18, flexDirection: 'row', gap: 7 }, progressDot: { flex: 1, height: 7, borderRadius: 5 }, helper: { marginTop: 11, fontSize: 11 },
  emptyTicket: { borderRadius: 24, padding: 22 }, emptyTag: { color: '#72DDB8', fontSize: 10, fontWeight: '900', letterSpacing: 1.2 }, emptyTitle: { color: 'white', fontSize: 25, fontWeight: '900', marginTop: 10 }, emptyCopy: { color: '#C7D7F2', fontSize: 14, lineHeight: 21, marginTop: 6 }, lightButton: { marginTop: 18, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  branchCard: { borderWidth: 1, borderRadius: 21, padding: 14, flexDirection: 'row', alignItems: 'center' }, pin: { width: 42, height: 42, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, pinText: { color: 'white' }, branchInfo: { marginLeft: 12, flex: 1 }, branchName: { fontSize: 16, fontWeight: '900' }, branchMeta: { marginTop: 3, fontSize: 12, fontWeight: '700' }, address: { marginTop: 3, fontSize: 11 }, sectionRow: { marginTop: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, sectionTitle: { fontSize: 18, fontWeight: '900' }, seeAll: { fontSize: 13, fontWeight: '800' }, serviceGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, serviceCard: { width: '48%', borderWidth: 1, borderRadius: 18, padding: 13 }, serviceIcon: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, serviceName: { marginTop: 10, fontSize: 13, fontWeight: '900' }, serviceWait: { marginTop: 4, fontSize: 11 },
});
