import { Colors } from '@/constants/theme';
import { useSession } from '@/context/session';
import { apiRequest } from '@/lib/api';
import { Ticket } from '@/lib/types';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, useColorScheme, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function TicketsScreen() {
  const color = Colors[useColorScheme() === 'dark' ? 'dark' : 'light']; const { token } = useSession(); const [tickets, setTickets] = useState<Ticket[]>([]); const [loading, setLoading] = useState(false);
  useFocusEffect(useCallback(() => { if (!token) return; let active = true; setLoading(true); apiRequest<{ data: Ticket[] }>('/tickets', token).then((response) => active && setTickets(response.data)).finally(() => active && setLoading(false)); return () => { active = false; }; }, [token]));
  if (!token) return <SafeAreaView style={[styles.screen, { backgroundColor: color.background }]}><View style={styles.center}><Text style={[styles.title, { color: color.text }]}>Your tickets</Text><Text style={[styles.copy, { color: color.textSecondary }]}>Sign in to view active and previous visits.</Text><Pressable onPress={() => router.push('/login')} style={[styles.button, { backgroundColor: color.primary }]}><Text style={styles.buttonText}>Sign in</Text></Pressable></View></SafeAreaView>;
  return <SafeAreaView style={[styles.screen, { backgroundColor: color.background }]} edges={['top']}><ScrollView contentContainerStyle={styles.content}><Text style={[styles.eyebrow, { color: color.primary }]}>YOUR VISITS</Text><Text style={[styles.title, { color: color.text }]}>Tickets</Text>{loading && <ActivityIndicator color={color.primary} />}{tickets.length === 0 && !loading ? <View style={[styles.empty, { backgroundColor: color.backgroundElement }]}><Text style={[styles.emptyTitle, { color: color.text }]}>No tickets yet</Text><Text style={[styles.copy, { color: color.textSecondary }]}>Your queue history will appear here.</Text></View> : tickets.map((ticket) => <Pressable key={ticket.id} onPress={() => ['waiting','called','serving','skipped','reserved'].includes(ticket.status) && router.push('/ticket')} style={[styles.card, { backgroundColor: color.backgroundElement, borderColor: color.border }]}><View style={[styles.numberBox, { backgroundColor: ticket.status === 'cancelled' ? '#FFF0F3' : color.backgroundSelected }]}><Text style={[styles.number, { color: ticket.status === 'cancelled' ? '#B42345' : color.primaryDark }]}>{ticket.number}</Text></View><View style={styles.info}><Text style={[styles.service, { color: color.text }]}>{ticket.service.name}</Text><Text style={[styles.branch, { color: color.textSecondary }]}>{ticket.branch.name}</Text><Text style={[styles.date, { color: color.textSecondary }]}>{new Date(ticket.waiting_since).toLocaleDateString()}</Text></View><View><Text style={[styles.status, { color: ticket.status === 'cancelled' ? '#B42345' : color.success }]}>{ticket.status}</Text><Text style={[styles.arrow, { color: color.textSecondary }]}>›</Text></View></Pressable>)}</ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 18, paddingBottom: 40 }, center: { flex: 1, justifyContent: 'center', padding: 28 }, eyebrow: { fontSize: 10, fontWeight: '900', letterSpacing: 1.4 }, title: { fontSize: 32, fontWeight: '900', marginTop: 7, marginBottom: 20 }, copy: { fontSize: 15, lineHeight: 23 }, button: { marginTop: 24, height: 50, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, buttonText: { color: 'white', fontWeight: '900' }, empty: { borderRadius: 22, padding: 24 }, emptyTitle: { fontSize: 18, fontWeight: '900', marginBottom: 6 }, card: { borderWidth: 1, borderRadius: 20, padding: 13, flexDirection: 'row', alignItems: 'center', marginBottom: 11 }, numberBox: { minWidth: 78, height: 52, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, number: { fontSize: 17, fontWeight: '900' }, info: { flex: 1, marginLeft: 12 }, service: { fontSize: 14, fontWeight: '900' }, branch: { marginTop: 3, fontSize: 12 }, date: { marginTop: 3, fontSize: 10 }, status: { textTransform: 'capitalize', fontSize: 11, fontWeight: '900', textAlign: 'right' }, arrow: { fontSize: 24, textAlign: 'right' } });
